apiVersion: v1
kind: BuildConfig
metadata:
  name: yogendrasri.inventory-management-svc-cr-yks.dev
  labels:
    app: inventory-management-svc-cr-yks
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
  source:
    git:
      uri: 'https://github.com/yogendrasri/inventory-management-svc-cr-yks.git'
      ref: dev
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: CLOUD_NAME
          value: openshift
        - name: NAMESPACE
          value: dev-cr-yks
        - name: BRANCH
          value: dev
